---
services:
  java-client:
    hostname: java-client
    container_name: java-client
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2:rw
    build:
      context: ./java-client
      dockerfile: localdev.dockerfile
    environment:
      - KAFKA_PORT=9092
      - KAFKA_ENDPOINT=broker
      - KAFKA_TOPIC=test-topic
    external_links:
      - broker